cal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    # url(r'^index/$', views.index, name='index'),
    # url(r'^$', views.CalendarView.as_view(), name='calendar'),
    # url(r'^event/new/$', views.event, name='event_new'),
    # url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='edit-event'),
    # path('index/', views.index, name='index'),
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/<int:pk>/', views.EventDetailView.as_view(), name='event-detail'),
    path('event/new/', views.EventCreateView.as_view(), name='new-event'),
    path('event/<int:pk>/edit/', views.EventUpdateView.as_view(), name='event-update'),
    path('event/<int:pk>/delete/', views.EventDeleteView.as_view(), name='event-delete'),
    path('events/', views.EventListView.as_view(), name='events'),
    path('create-reminder/', views.ReminderCreateView.as_view(), name='create-reminder'),
    path('reminders/', views.index, name='index'),
    path('my-events/', views.UserEventView.as_view(), name='user-events'),
    path('send-reminder/', views.send_reminder, name='send-reminder'),

]

scmsngo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('home/', ),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('profile-detail/<int:pk>/', user_views.ProfileDetailView.as_view(), name='profile-detail'),
    path('members/', user_views.ProfileListView.as_view(), name='members'),
    path('activate/<uidb64>/<token>/', user_views.activate_account, name='activate'),
    path('', include('announcements.urls')),
    path('calendar/', include('cal.urls')),
    path('ngo/', include('ngodocs.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image

from announcements.models import Tag


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    image = models.ImageField(default='default.png', upload_to='events')
    date_posted = models.DateTimeField(default=timezone.now)
    tag = models.ManyToManyField(Tag)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    facebookurl = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        size = 300
        if img.height > size or img.width > size:
            output_size = (size, size)
            img.thumbnail(output_size)
            img.save(self.image.path)

    @property
    def get_html_url(self):
        url = reverse('cal:event-detail', args=(self.id,))
        return f'<a href="{url}">{ self.title }</a>'

    def get_absolute_url(self):
        return reverse('cal:event-detail', kwargs={'pk': self.pk})


class Reminder(models.Model):
    reminder_date = models.DateField()
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'Reminder no. { self.pk }'

    def save(self, **kwargs):
        super().save()

    def get_absolute_url(self):
        return reverse('cal:create-reminder')

cal/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, DateTimeInput, DateInput
from bootstrap_modal_forms.forms import BSModalForm
from .models import Event, Reminder


class EventForm(ModelForm):

    class Meta:
        model = Event
        widgets = {
            'start_time': DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = ['title', 'description', 'start_time', 'end_time', 'image', 'tag', 'facebookurl']
        labels = {'facebookurl': 'Facebook event link'}

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)


class ReminderForm(ModelForm):
    # member = forms.ModelChoiceField(User.objects)
    # event = forms.ModelChoiceField(Event.objects)

    class Meta:
        model = Reminder
        widgets = {
            'reminder_date': DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
        }
        fields = ['reminder_date']

        def __init__(self, *args, user, event, **kwargs):
            super(ReminderForm, self).__init__(*args, **kwargs)

            # self.fields['member'].queryset = User.objects.filter(member=user)
            # self.fields['event'].queryset = Event.objects.filter(event=event)
            # input_formats to parse HTML5 datetime-local input to date field
            self.fields['reminder_date'].input_formats = ('%Y-%m-%d',)

cal/views.py
from django.contrib.auth.decorators import login_required
from bootstrap_modal_forms.generic import BSModalCreateView
from django.shortcuts import render, get_object_or_404, redirect
from datetime import datetime, timedelta, date
from django.core.mail import EmailMessage
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.utils.safestring import mark_safe
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import *
from .utils import Calendar
from .forms import EventForm, ReminderForm
import calendar


class EventListView(LoginRequiredMixin, ListView):
    model = Event
    template_name = 'cal/events.html'
    context_object_name = 'events'
    ordering = ['-start_time']
    paginate_by = 5


class EventDetailView(LoginRequiredMixin, DetailView):
    model = Event

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        self.request.session['id'] = self.object.pk
        return context


class EventDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Event
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class CalendarView(LoginRequiredMixin, ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))
        # instantiate with today's year and date
        cal = Calendar(d.year, d.month)
        # call the formatmonth method with returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


class EventCreateView(LoginRequiredMixin, CreateView):
    # model = Event
    form_class = EventForm
    template_name = 'cal/event_form.html'

    def form_valid(self, form_class):
        form_class.instance.author = self.request.user
        return super().form_valid(form_class)


class EventUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Event
    form_class = EventForm

    def form_valid(self, form_class):
        form_class.instance.author = self.request.user
        return super().form_valid(form_class)

    def test_func(self):
        event = self.get_object()
        if self.request.user == event.author:
            return True
        return False


class ReminderCreateView(LoginRequiredMixin, CreateView):
    form_class = ReminderForm
    template_name = 'cal/create_reminder.html'

    def form_valid(self, form_class):
        form_class.instance.member = self.request.user
        myevent_id = self.request.session.get('id')
        form_class.instance.event = Event.objects.get(id=myevent_id)
        return super().form_valid(form_class)
    # success_message = 'Success: Your reminder has been created'
    # success_url = reverse_lazy('event-detail')


class UserEventView(LoginRequiredMixin, ListView):
    model = Event
    template_name = 'cal/events.html'
    context_object_name = 'events'

    def get_queryset(self):
        qs = super().get_queryset()
        # qs = Announcement.objects.filter(author=self.request.user)
        return qs.filter(author=self.request.user)


def index(request):
    return HttpResponse('Done!')


def send_reminder(request):
    reminders = Reminder.objects.filter(reminder_date=date.today())
    if reminders:
        email_subject = 'You have an upcoming event!'
        for reminder in reminders:
            html_message = render_to_string('cal/reminder_message.html', {'reminder': reminder,})
            # plain_message = strip_tags(html_message)
            to_email = reminder.member.email
            email = EmailMessage(email_subject, html_message, to=[to_email])
            email.content_subtype = 'html'
            email.send()
            Reminder.objects.filter(id=reminder.id).delete()
        messages.success(request, f'Reminder sent to users!')
        return redirect('ngo-about')
    else:
        return redirect('announcements-home')

cal/templates/cal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'announcements/main.css' %}">

    {% if title %}
        <title>Camara - {{ title }}</title>
    {% else %}
        <title>Camara</title>
    {% endif %}
</head>
<body>
   <header class="site-header" >
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="height:70px" >
        <div class="container">

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        My NGO
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'ngo-about' %}">About</a>
                        <a class="dropdown-item" href="{% url 'members' %}">Members</a>
                        <a class="dropdown-item" href="{% url 'ngo-documents' %}">Documents</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Materials</a>
                    </div>
                </li>
                <a class="nav-item nav-link" href="{% url 'news' %}">News</a>
                <a class="nav-item nav-link" href="{% url 'announcements-home' %}">Announcements</a>
                <a class="nav-item nav-link" href="{% url 'cal:calendar' %}">Calendar</a>
                <a class="nav-item nav-link" href="{% url 'cal:events' %}">Events</a>
                <a class="nav-item nav-link" href="#">Stats</a>
                <a class="nav-item nav-link" href="{% url 'search' %}">Search</a>
                <!--              <form class="form-inline">-->
                <!--                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
                <!--                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
                <!--              </form>-->
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Add new
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'announcement-create' %}">Add announcement</a>
                        <a class="dropdown-item" href="{% url 'cal:new-event' %}">Add event</a>
                        <a class="dropdown-item" href="#">Add document</a>
                        {% for group_for in request.user.groups.all %}
                            {% if group_for.name == 'Boardie' %}
                            <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'register' %}">Register new member</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </li>
                <a class="nav-item nav-link" href="{% url 'profile-detail' user.profile.id %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock content %}
        </div>
      </div>
    </main>
    <!--<div class="footer">
        <img class="logo-camara" src="{% static 'logo.png' %}" >
    </div>-->
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block content %}
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
        <a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
        <a class="btn btn-info right" href="{% url 'cal:new-event' %}"> New Event </a>
    </div>
     {{ calendar }}
{% endblock content %}

cal/templates/cal/create_reminder.html
{% extends "announcements/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="form form-table">
        {{ form|crispy }}
        <tr>
            <td colspan="2">
                <button type="submit" class="btn btn-info right">Save reminder</button>
            </td>
        </tr>
    </table>
</form>

<!--<a class="btn btn-outline-info" href="{% url 'cal:send-reminder' %}">SEND MAIL</a>-->

{% endblock content %}
<!--<form method="post" action="">-->
<!--  {% csrf_token %}-->

<!-- <div class="modal-header">-->
<!--    <h5 class="modal-title">Create reminder</h5>-->
<!--    <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--      <span aria-hidden="true">&times;</span>-->
<!--    </button>-->
<!--  </div>-->

<!--  <div class="modal-body">-->
<!--    {% for field in form %}-->
<!--      <div class="form-group{% if field.errors %} invalid{% endif %}">-->
<!--        <label for="{{ field.id_for_label }}">{{ field.label }}</label>-->
<!--        {{ field }}-->
<!--        {% for error in field.errors %}-->
<!--          <p class="help-block">{{ error }}</p>-->
<!--        {% endfor %}-->
<!--      </div>-->
<!--    {% endfor %}-->
<!--  </div>-->

<!--  <div class="modal-footer">-->
<!--    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
<!--    <button type="button" class="submit-btn btn btn-primary">Save</button>-->
<!--  </div>-->

<!--</form>-->

cal/templates/cal/event_confirm_delete.html
{% extends "announcements/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Event</legend>
                <h2>Are you sure you want to delete the event "{{ object.title }}"?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'cal:event-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

cal/templates/cal/event_detail.html
{% extends "announcements/base.html" %}
{% block content %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted">posted on {{ event.date_posted|date:"F d, Y" }}</small>
            {% if object.author == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'cal:event-update' event.id %}">Edit</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'cal:event-delete' event.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
        <div class="d-flex justify-content-between">
            <h2 class="article-title">{{ event.title }}</h2>
<!--            <div class="modal fade" tabindex="-1" role="dialog" id="modal">-->
<!--                <div class="modal-dialog" role="document">-->
<!--                    <div class="modal-content">-->

<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
                <a class="btn btn-outline-info" href="{% url 'cal:create-reminder' %}">Set reminder</a>
        </div>
        <p class="article-content">{{ event.start_time|date:"H:m" }} - {{ event.end_time|date:"H:m" }}, {{ event.start_time|date:"F d" }} - {{ event.end_time|date:"F d, Y" }}</p>
        <p class="article-content">{{ event.description }}</p>
        {% for tag in event.tag.all %}
            <small class="text-muted">{{ tag }} </small>
        {% endfor %}
        <div class="d-flex justify-content-center">
            <img src="{{ event.image.url }}" alt="Unable to load image" class="w3-hover-opacity">
        </div>

<!--        <script type="text/javascript">-->
<!--                        $(function() {-->

<!--                            $(".create-reminder").modalForm({-->
<!--                                formURL: "{% url 'cal:create-reminder' %}"-->
<!--                            });-->

<!--                        });-->



<!--        </script>-->
    </div>
</article>

{% endblock content %}

cal/templates/cal/event_form.html
{% extends 'announcements/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
New Event
{% endblock %}

{% block content %}

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table class="form form-table">
        {{ form|crispy }}
        <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Save </button></td></tr>
      </table>
    </form>
{% endblock %}

cal/templates/cal/events.html
{% extends "announcements/base.html" %}

{% block content %}

<div class="card-columns">
    {% for event in events %}
    <div class="card">
        <img class="card-img-top img-fluid" src="{{ event.image.url }}" alt="Unable to load image">
        <div class="card-block">
            <div class="card-body">
                <h5><a class="card-title" href="{% url 'cal:event-detail' event.id %}">{{ event.title}}</a></h5>
                <p class="card-text">{{ event.start_time|date:"j F Y, H:i" }}</p>
                <p class="card-text">{{ event.description}}</p>
            </div>
            <div class="card-footer">
                {% for tag in event.tag.all %}
                    <small class="text-muted">{{ tag }} </small>
                {% endfor %}
                <small><a class="mr-2" href="{% url 'profile-detail' event.author.profile.id %}">posted by {{ event.author }}</a></small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<br/><br/><br/>
{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}
{% endblock content %}

cal/templates/cal/reminder_message.html
{% autoescape off %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>{{ reminder.event.title }} reminder!</title>
</head>
<body>
<h3>Hi, {{ reminder.member.first_name }}!</h3>

<p>Don't forget about your event, {{ reminder.event.title }}, coming up on {{ reminder.event.start_time|date:"F d, Y" }}
    at {{ reminder.event.start_time|date:"H:m" }}! </p>

<p>For more details, login to your account at http://{{ domain }}{% url 'login' %}.</p>

<p>Have a great day!</p>
</body>
</html>
{% endautoescape %}