announcements/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserAnnouncementView,
    NewsListView,
)
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('announcements/', PostListView.as_view(), name='announcements-home'),
    path('announcement/<int:pk>/', PostDetailView.as_view(), name='announcement-detail'),
    path('announcement/new/', PostCreateView.as_view(), name='announcement-create'),
    path('announcement/<int:pk>/update/', PostUpdateView.as_view(), name='announcement-update'),
    path('announcement/<int:pk>/delete/', PostDeleteView.as_view(), name='announcement-delete'),
    path('about/', views.about, name='announcements-about'),
    path('search/', views.search, name='search'),
    path('my-announcements/', UserAnnouncementView.as_view(), name='user-announcements'),
    path('news/', NewsListView.as_view(), name='news'),

]

cal/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    # url(r'^index/$', views.index, name='index'),
    # url(r'^$', views.CalendarView.as_view(), name='calendar'),
    # url(r'^event/new/$', views.event, name='event_new'),
    # url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='edit-event'),
    # path('index/', views.index, name='index'),
    path('', views.CalendarView.as_view(), name='calendar'),
    path('event/<int:pk>/', views.EventDetailView.as_view(), name='event-detail'),
    path('event/new/', views.EventCreateView.as_view(), name='new-event'),
    path('event/<int:pk>/edit/', views.EventUpdateView.as_view(), name='event-update'),
    path('event/<int:pk>/delete/', views.EventDeleteView.as_view(), name='event-delete'),
    path('events/', views.EventListView.as_view(), name='events'),
    path('create-reminder/', views.ReminderCreateView.as_view(), name='create-reminder'),
    path('reminders/', views.index, name='index'),
    path('my-events/', views.UserEventView.as_view(), name='user-events'),
    path('send-reminder/', views.send_reminder, name='send-reminder'),

]

scmsngo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('home/', ),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('profile-detail/<int:pk>/', user_views.ProfileDetailView.as_view(), name='profile-detail'),
    path('members/', user_views.ProfileListView.as_view(), name='members'),
    path('activate/<uidb64>/<token>/', user_views.activate_account, name='activate'),
    path('', include('announcements.urls')),
    path('calendar/', include('cal.urls')),
    path('ngo/', include('ngodocs.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

announcements/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        super().save()


class Announcement(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    last_modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    image = models.ImageField(default='default.png', upload_to='announcements')
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        # size = 250
        # if img.height > size or img.width > size:
        #     output_size = (size, size)
        #     img.thumbnail(output_size)
        #     img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('announcement-detail', kwargs={'pk': self.pk})


class News(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    event = models.ForeignKey("cal.Event", on_delete=models.CASCADE, null=True, blank=True)
    document = models.ForeignKey("ngodocs.NGODocument", on_delete=models.CASCADE, null=True, blank=True)
    date_posted = models.DateTimeField()

    def __str__(self):
        return self.title

announcements/forms.py
from django import forms


class SearchForm(forms.Form):
    keyword = forms.CharField(label='Search word', max_length=20)

announcements/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Announcement, News
from .filters import AnnouncementFilter, EventFilter, NGODocumentFilter
from .forms import SearchForm
from cal.models import Event
from ngodocs.models import NGODocument
import django_filters

# def home(request):
#     announcements = Announcement.objects.all()
#     myFilter = AnnouncementFilter(request.GET, queryset=announcements)
#     announcements = myFilter.qs
#
#     context = {
#         'myFilter': myFilter,
#         'announcements': announcements
#
#     }
#     return render(request, 'announcements/home.html', context)
    # return HttpResponse('<h1>Homie</h1')


def homepage(request):
    if request.user.is_authenticated:
        return redirect('ngo-about')
    else:
        return render(request, 'announcements/homepage.html')


@login_required(login_url='login')
def search(request):
    # form = SearchForm
    if request.method == "GET":
        form = SearchForm(request.GET)
        # a = request.GET
        keyword = form['keyword'].value()
        announcements = Announcement.objects.all()
        events = Event.objects.all()
        ngodocs = NGODocument.objects.all()
        # myFilterGen = GeneralFilter(request.GET, queryset=announcements, typ=1)
        myFilterAnn = AnnouncementFilter({"content": keyword}, queryset=announcements)
        # s_keyword = myFilterAnn.data['content']
        myFilterEvents = EventFilter({"title": keyword}, queryset=events)
        myFilterNGODocs = NGODocumentFilter({"document": keyword}, queryset=ngodocs)
        announcements = myFilterAnn.qs
        events = myFilterEvents.qs
        ngodocs = myFilterNGODocs.qs

        # results = announcements | events | ngodocs
        context = {
            # 'myFilterGen': myFilterGen,
            # 'myFilterAnn': myFilterAnn,
            'form': SearchForm,
            'announcements': announcements.order_by('-date_posted'),
            # 'myFilterEvents': myFilterEvents,
            'events': events.order_by('-start_time'),
            # # 'myFilterNGODocs': myFilterNGODocs,
            'ngodocs': ngodocs.order_by('-date_posted'),
        }
        # context = {
        #     'myFilterAnn': myFilterAnn,
        #     'myFilterEvents': myFilterEvents,
        #     'myFilterNGODocs': myFilterNGODocs,
        #     'results': results,
        # }
        return render(request, 'announcements/search.html', context)


class PostListView(LoginRequiredMixin, ListView):
    model = Announcement
    template_name = 'announcements/home.html'
    context_object_name = 'announcements'
    ordering = ['-date_posted']
    paginate_by = 3


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Announcement


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Announcement
    fields = ['title', 'content', 'image', 'tag']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Announcement
    fields = ['title', 'content', 'image', 'tag']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Announcement
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class UserAnnouncementView(LoginRequiredMixin, ListView):
    model = Announcement
    template_name = 'announcements/home.html'
    context_object_name = 'announcements'
    ordering = ['-date_posted']

    def get_queryset(self):
        qs = super().get_queryset()
        # qs = Announcement.objects.filter(author=self.request.user)
        return qs.filter(author=self.request.user)


class NewsListView(LoginRequiredMixin, ListView):
    model = News
    template_name = 'announcements/news.html'
    context_object_name = 'newslist'
    ordering = ['-date_posted']
    paginate_by = 20


@login_required(login_url='login')
def about(request):
    return render(request, 'announcements/about.html')

announcements/templates/announcements/about.html
{% extends "announcements/base.html" %}
{% block content %}
    <h1>About is All about, how about?</h1>
{% endblock content %}

announcements/templates/announcements/announcement_confirm_delete.html
{% extends "announcements/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'announcement-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

announcements/templates/announcements/announcement_detail.html
{% extends "announcements/base.html" %}

{% block content %}

  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'announcement-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'announcement-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
      <img src="{{ announcement.image.url }}" alt="Unable to load image" style="width:100%" class="w3-hover-opacity">
      {% for tag in object.tag.all %}
          <small class="text-muted">{{ tag }} </small>
      {% endfor %}
    </div>
  </article>

{% endblock content %}

announcements/templates/announcements/announcement_form.html
{% extends "announcements/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Announcement</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

announcements/templates/announcements/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'announcements/main.css' %}">


    {% if title %}
    <title>Camara - {{ title }}</title>
    {% else %}
    <title>Camara</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top" style="height:70px">
        <div class="container">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            My NGO
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'ngo-about' %}">About</a>
                            <a class="dropdown-item" href="{% url 'members' %}">Members</a>
                            <a class="dropdown-item" href="{% url 'ngo-documents' %}">Documents</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'ngo-materials' %}">Materials</a>
                        </div>
                    </li>
                    <a class="nav-item nav-link" href="{% url 'news' %}">News</a>
                    <a class="nav-item nav-link" href="{% url 'announcements-home' %}">Announcements</a>
                    <a class="nav-item nav-link" href="{% url 'cal:calendar' %}">Calendar</a>
                    <a class="nav-item nav-link" href="{% url 'cal:events' %}">Events</a>
                    <a class="nav-item nav-link" href="#">Stats</a>
                    <a class="nav-item nav-link" href="{% url 'search' %}">Search</a>
                    <!--              <form class="form-inline">-->
                    <!--                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
                    <!--                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
                    <!--              </form>-->
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Add new
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'announcement-create' %}">Add announcement</a>
                            <a class="dropdown-item" href="{% url 'cal:new-event' %}">Add event</a>
                            <a class="dropdown-item" href="{% url 'document-create' %}">Add document</a>
                            {% for group_for in request.user.groups.all %}
                                {% if group_for.name == 'Boardie' %}
                                <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'register' %}">Register new member</a>
                                        <a class="dropdown-item" href="{% url 'cal:send-reminder' %}">Send reminders</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </li>
                    <a class="nav-item nav-link" href="{% url 'profile-detail' user.profile.id %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            <div class="searchthing">
                {% block searchthing %}{% endblock searchthing %}
            </div>
            {% block content %}{% endblock content %}
        </div>
        {% if user.is_authenticated %}
        <div class="col-md-4">
            <div class="content-section">
                <h3>{{ user.username }}'s sidebar</h3>
                <p class='text-muted'>
                <ul class="list-group">
                    <a class="list-group-item list-group-item-light" href="{% url 'user-announcements' %}">My announcements</a>
                    <a class="list-group-item list-group-item-light" href="{% url 'cal:user-events' %}">My events</a>
                    <a class="list-group-item list-group-item-light" href="{% url 'user-docs' %}">My documents</a>
                </ul>
                </p>
            </div>
        </div>
        {% endif %}

    </div>
</main>
<!--<div class="footer">
    <img class="logo-camara" src="{% static 'logo.png' %}" >
</div>-->
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <!-- You can alternatively load the minified version -->
<!--    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>-->
</body>
</html>

announcements/templates/announcements/home.html
{% extends "announcements/base.html" %}

{% block content %}

    {% for announcement in announcements %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'profile-detail' announcement.author.profile.id %}">{{ announcement.author }}</a>
             <small class="text-muted"> {{ announcement.date_posted|date:"j F Y, H:i" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'announcement-detail' announcement.id %}">{{ announcement.title }}
            </a></h2>
            <p class="article-content">{{ announcement.content }}</p>
            <div class="d-flex justify-content-center">
                <img class="card-img-bottom" src="{{ announcement.image.url }}" alt="Unable to load image" style="width:50%"/>
            </div>
            <div class="d-flex justify-content-end">
                {% for tag in announcement.tag.all %}
                    <small class="text-muted p-2"> {{ tag }} </small>
                {% endfor %}
            </div>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %} 

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                 <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

announcements/templates/announcements/news.html
{% extends "announcements/base.html" %}

{% block content %}
 {% for news in newslist %}
        <article class="media content-section m-0">
          <div class="media-body p-0">
             {% if news.event %}
                <p class="d-flex justify-content-between"><h2><a class="article-title" href="{% url 'cal:event-detail' news.event.id %}">{{ news.title }}</a></h2> {{ news.content }}</p>
                <div class="d-flex justify-content-between">
                    <small class="text-muted"><a class="mr-2" href="{% url 'profile-detail' news.event.author.profile.id %}">added by {{ news.event.author }} </a>on {{ news.date_posted|date:"j F Y, H:i" }}</small>
                    <div>
                        {% for tag in news.event.tag.all %}
                            <small class="text-muted">{{ tag }} </small>
                        {% endfor %}
                    </div>
                </div>
             {% elif news.document %}
                <p class="d-flex justify-content-between"><h2><a class="article-title" href="{{ news.document.document.url }}">{{ news.title }}</a></h2> {{ news.content }}</p>
                <div class="d-flex justify-content-between">
                    <small class="text-muted"><a class="mr-2" href="{% url 'profile-detail' news.document.author.profile.id %}">added by {{ news.document.author }} </a>on {{ news.date_posted|date:"j F Y, H:i" }}</small>
                    <div>
                        {% for tag in news.document.tag.all %}
                            <small class="text-muted">{{ tag }} </small>
                        {% endfor %}
                    </div>
                </div>
             {% endif %}
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                 <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

announcements/templates/announcements/search.html
{% extends "announcements/base.html" %}
{% load crispy_forms_tags %}

{% block searchthing %}
  <form method="get">
<!--            {{ myFilterAnn.form|crispy }}-->
<!--            {{ myFilterEvents.form|crispy }}-->
<!--            {{ myFilterNGODocs.form|crispy }}-->
      {{ form|crispy }}
            <button class="btn btn-info" type="submit">Search</button>
  </form>
  <br/>
{% endblock searchthing %}

{% block content %}
{% if announcements or events or ngodocs %}
    {% if announcements %}
    <h5> Results in announcements: </h5>
    {% for announcement in announcements %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="#">{{ announcement.author }}</a>
                 <small class="text-muted"> {{ announcement.date_posted|date:"j F Y, H:i" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'announcement-detail' announcement.id %}">{{ announcement.title }}
                </a></h2>
                <p class="article-content">{{ announcement.content }}</p>
                <img src="{{ announcement.image.url }}" alt="Unable to load image" style="width:200px">
                <div class="d-flex justify-content-end">
                {% for tag in announcement.tag.all %}
                    <small class="text-muted pr-1">{{ tag }} </small>
                {% endfor %}
                </div>
              </div>
            </article>
        {% endfor %}
        {% endif %}
        {% if events %}
        <h5> Results in events: </h5>
        {% for event in events %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="#">{{ event.author }}</a>
                 <small class="text-muted"> {{ event.start_time|date:"j F Y, H:i" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'cal:event-detail' event.id %}">{{ event.title }}
                </a></h2>
                <p class="article-content">{{ event.description }}</p>
                <img src="{{ event.image.url }}" alt="Unable to load image" style="width:200px">
                <div class="d-flex justify-content-end">
                    {% for tag in event.tag.all %}
                        <small class="text-muted pr-1">{{ tag }} </small>
                    {% endfor %}
                </div>
              </div>
            </article>
        {% endfor %}
        {% endif %}
        {% if ngodocs %}
        <h5> Results in NGO documents: </h5>
        {% for ngodoc in ngodocs %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="#">{{ ngodoc.author }}</a>
                 <small class="text-muted"> {{ ngodoc.date_posted|date:"j F Y, H:i" }}</small>
                </div>
                <h2><a class="article-title" href="#">{{ ngodoc }}
                </a></h2>
                <div class="d-flex justify-content-between">
                <small class="text-muted">status: {{ ngodoc.status }}</small>
                    <div>
                    {% for tag in ngodoc.tag.all %}
                          <small class="text-muted pr-1">{{ tag }} </small>
                    {% endfor %}
                    </div>
                </div>
              </div>
            </article>
        {% endfor %}
        {% endif %}
        {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                     <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="{{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

        {% endif %}
    {% else %}
        Sorry, no results match you search! Try with a different combination.
    {% endif %}


{% endblock content %}